# Generated by Django 4.0.3 on 2022-03-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(default='x', on_delete=django.db.models.deletion.CASCADE, to='myapp.publication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
