# Generated by Django 4.0.3 on 2022-03-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_book_publication_alter_publication_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication',
        ),
    ]
