# Generated by Django 4.0.3 on 2022-03-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_book_publication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
