# Generated by Django 4.0.3 on 2022-03-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_publication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
