# Generated by Django 4.0.3 on 2022-03-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.publication'),
        ),
    ]
