# Generated by Django 4.0.3 on 2022-03-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
