# Generated by Django 4.0.3 on 2022-03-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_book_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='myapp.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'چاپ شده')], max_length=1, verbose_name='وضغیت انتشار'),
        ),
    ]
