# Generated by Django 4.0.3 on 2022-03-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free', models.BooleanField(default=False)),
                ('limited_discount', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(null=True, verbose_name='محتوا در سایت'),
        ),
        migrations.AddField(
            model_name='category',
            name='msubtitle',
            field=models.CharField(max_length=200, null=True, verbose_name='زیرعنوان در سایت'),
        ),
        migrations.AddField(
            model_name='category',
            name='mtitle',
            field=models.CharField(max_length=200, null=True, verbose_name='  عنوان در سایت'),
        ),
    ]
