# Generated by Django 4.0.3 on 2022-03-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_audiobook_category_description_category_msubtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='books', to='myapp.category', verbose_name='دسته بندی'),
        ),
    ]
