# Generated by Django 4.0.3 on 2022-03-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیح عنوان'),
        ),
    ]
