# Generated by Django 4.0.3 on 2022-03-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_book_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='x', max_length=200, verbose_name='نویسنده کتاب'),
            preserve_default=False,
        ),
    ]
