# Generated by Django 4.0.3 on 2022-03-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mauthor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='گردآورنده'),
        ),
    ]
