# Generated by Django 4.0.3 on 2022-03-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_book_mauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='محتوا در سایت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='msubtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='زیرعنوان در سایت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='mtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='  عنوان در سایت'),
        ),
    ]
