# Generated by Django 4.0.3 on 2022-03-10 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_book_price_alter_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedis', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تخفیف تا')),
                ('amountdis', models.IntegerField(default=0, verbose_name='میزان تخفیف')),
            ],
        ),
        migrations.DeleteModel(
            name='AudioBook',
        ),
    ]
