# Generated by Django 4.0.3 on 2022-03-10 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_disscount_delete_audiobook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='disscount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='disscount', to='myapp.disscount', verbose_name='تخفیف'),
        ),
    ]
