# Generated by Django 4.0.3 on 2022-03-10 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_book_disscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='disscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disscount', to='myapp.disscount', verbose_name='تخفیف'),
        ),
    ]
