# Generated by Django 4.0.3 on 2022-03-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_book_time_disscount_alter_book_disscount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='disscount',
        ),
        migrations.RemoveField(
            model_name='book',
            name='time_disscount',
        ),
    ]
