# Generated by Django 4.0.3 on 2022-03-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_book_disscount_remove_book_time_disscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='disscount',
            field=models.IntegerField(blank=True, null=True, verbose_name='درصد تخفیف'),
        ),
    ]
