# Generated by Django 4.0.3 on 2022-03-10 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_book_disscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time_disscount',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=' تخفیف تا '),
        ),
    ]
