# Generated by Django 4.0.3 on 2022-03-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_book_time_disscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='disscount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='درصد تخفیف'),
        ),
    ]
