# Generated by Django 4.0.3 on 2022-03-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='x', max_length=80),
            preserve_default=False,
        ),
    ]
