# Generated by Django 4.0.3 on 2022-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='ali@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
