# Generated by Django 4.0.3 on 2022-03-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2022-10-03'),
            preserve_default=False,
        ),
    ]
