# Generated by Django 4.0.3 on 2022-03-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_alter_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='myapp.myipaddress', verbose_name='بازدیدها'),
        ),
    ]
