# Generated by Django 4.0.3 on 2022-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_myipaddress_book_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='hits',
        ),
        migrations.AddField(
            model_name='category',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='myapp.myipaddress', verbose_name='بازدیدها'),
        ),
    ]
