# Generated by Django 4.0.3 on 2022-03-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_remove_book_hits_category_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hits',
        ),
    ]
