# Generated by Django 4.0.3 on 2022-03-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_remove_category_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='myapp.myipaddress', verbose_name='بازدیدها'),
        ),
    ]
