# Generated by Django 4.0.3 on 2022-03-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_remove_category_hits_book_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='myipaddress',
            name='name',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
    ]
