# Generated by Django 4.0.3 on 2022-03-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_alter_myipaddress_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='hits',
        ),
    ]
