# Generated by Django 4.0.3 on 2022-03-16 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_remove_book_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='myapp.BookHit', to='myapp.myipaddress', verbose_name='بازدیدها'),
        ),
        migrations.AddField(
            model_name='bookhit',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.book'),
        ),
        migrations.AddField(
            model_name='bookhit',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myipaddress'),
        ),
    ]
