# Generated by Django 4.0.3 on 2022-04-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_getpass_user_passs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passs',
        ),
    ]
