# Generated by Django 4.0.3 on 2022-04-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_remove_user_passs'),
    ]

    operations = [
        migrations.AddField(
            model_name='getpass',
            name='passs',
            field=models.CharField(default='1234', max_length=4),
            preserve_default=False,
        ),
    ]
