# Generated by Django 4.0.3 on 2022-04-28 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_getpass_passs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getpass',
            name='passs',
        ),
        migrations.AddField(
            model_name='getpass',
            name='pakk',
            field=models.ForeignKey(default='1234', on_delete=django.db.models.deletion.CASCADE, related_name='repl', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
