# Generated by Django 4.0.3 on 2022-04-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_remove_getpass_passs_getpass_pakk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getpass',
            name='pakk',
        ),
    ]
