# Generated by Django 4.0.3 on 2022-04-30 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_remove_getpass_pakk'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='uhits', through='myapp.UserHit', to=settings.AUTH_USER_MODEL, verbose_name='کتابهای من'),
        ),
        migrations.AddField(
            model_name='userhit',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.book'),
        ),
        migrations.AddField(
            model_name='userhit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
