# Generated by Django 4.0.3 on 2022-04-30 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_userhit_alter_book_hits_userhit_book_userhit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uhits',
            field=models.ManyToManyField(blank=True, related_name='uhits', through='myapp.UserHit', to=settings.AUTH_USER_MODEL, verbose_name='کتابهای من'),
        ),
        migrations.AlterField(
            model_name='book',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='myapp.BookHit', to='myapp.myipaddress', verbose_name='بازدیدها'),
        ),
    ]
