# Generated by Django 4.0.3 on 2022-04-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_book_uhits_alter_book_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uhits',
        ),
        migrations.DeleteModel(
            name='UserHit',
        ),
    ]
