# Generated by Django 4.0.3 on 2022-05-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
