# Generated by Django 4.0.3 on 2022-05-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0072_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timebuy', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
