# Generated by Django 4.0.3 on 2022-05-07 18:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_currenttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(choices=[(datetime.datetime(2022, 4, 30, 22, 51, 32, 249908), 'یک هفته '), (datetime.datetime(2022, 4, 7, 22, 51, 32, 249908), 'یک ماه'), (datetime.datetime(2022, 2, 6, 22, 51, 32, 249908), ' سه ماه'), (datetime.datetime(2021, 11, 8, 22, 51, 32, 249908), 'شش ماه'), (datetime.datetime(2021, 5, 7, 22, 51, 32, 249908), 'یک سال')], default=django.utils.timezone.now, verbose_name='عضویت بی نهایت تا'),
        ),
    ]
