# Generated by Django 4.0.3 on 2022-05-09 19:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0074_alter_user_special_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(choices=[(datetime.datetime(2022, 5, 2, 23, 39, 13, 696008), 'یک هفته '), (datetime.datetime(2022, 4, 9, 23, 39, 13, 696008), 'یک ماه'), (datetime.datetime(2022, 2, 8, 23, 39, 13, 696008), ' سه ماه'), (datetime.datetime(2021, 11, 10, 23, 39, 13, 696008), 'شش ماه'), (datetime.datetime(2021, 5, 9, 23, 39, 13, 696008), 'یک سال')], default=django.utils.timezone.now, verbose_name='عضویت بی نهایت تا'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mybag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mybags', to=settings.AUTH_USER_MODEL)),
                ('mybooks', models.ManyToManyField(related_name='profiles', to='myapp.book', verbose_name='کتابهای من')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
