# Generated by Django 4.0.3 on 2022-05-10 11:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_alter_user_special_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='05/10/2022'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(choices=[(datetime.datetime(2022, 5, 3, 15, 39, 45, 103842), 'یک هفته '), (datetime.datetime(2022, 4, 10, 15, 39, 45, 103842), 'یک ماه'), (datetime.datetime(2022, 2, 9, 15, 39, 45, 103842), ' سه ماه'), (datetime.datetime(2021, 11, 11, 15, 39, 45, 103842), 'شش ماه'), (datetime.datetime(2021, 5, 10, 15, 39, 45, 103842), 'یک سال')], default=django.utils.timezone.now, verbose_name='عضویت بی نهایت تا'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mybag',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mybags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
