# Generated by Django 4.0.3 on 2022-05-10 11:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0076_userprofile_created_alter_user_special_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created',
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(choices=[(datetime.datetime(2022, 5, 3, 15, 41, 13, 13268), 'یک هفته '), (datetime.datetime(2022, 4, 10, 15, 41, 13, 13268), 'یک ماه'), (datetime.datetime(2022, 2, 9, 15, 41, 13, 13268), ' سه ماه'), (datetime.datetime(2021, 11, 11, 15, 41, 13, 13268), 'شش ماه'), (datetime.datetime(2021, 5, 10, 15, 41, 13, 13268), 'یک سال')], default=django.utils.timezone.now, verbose_name='عضویت بی نهایت تا'),
        ),
    ]
