# Generated by Django 4.0.3 on 2022-05-10 11:12

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0077_remove_userprofile_created_alter_user_special_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2022-05-10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(choices=[(datetime.datetime(2022, 5, 3, 15, 42, 14, 701020), 'یک هفته '), (datetime.datetime(2022, 4, 10, 15, 42, 14, 701020), 'یک ماه'), (datetime.datetime(2022, 2, 9, 15, 42, 14, 701020), ' سه ماه'), (datetime.datetime(2021, 11, 11, 15, 42, 14, 701020), 'شش ماه'), (datetime.datetime(2021, 5, 10, 15, 42, 14, 701020), 'یک سال')], default=django.utils.timezone.now, verbose_name='عضویت بی نهایت تا'),
        ),
    ]
