# Generated by Django 4.0.3 on 2022-05-10 11:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0079_alter_user_special_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='puser',
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(choices=[(datetime.datetime(2022, 5, 3, 16, 23, 7, 371959), 'یک هفته '), (datetime.datetime(2022, 4, 10, 16, 23, 7, 371959), 'یک ماه'), (datetime.datetime(2022, 2, 9, 16, 23, 7, 371959), ' سه ماه'), (datetime.datetime(2021, 11, 11, 16, 23, 7, 371959), 'شش ماه'), (datetime.datetime(2021, 5, 10, 16, 23, 7, 371959), 'یک سال')], default=django.utils.timezone.now, verbose_name='عضویت بی نهایت تا'),
        ),
    ]
