# Generated by Django 4.0.3 on 2022-05-10 11:56

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0080_rename_user_userprofile_puser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(choices=[(datetime.datetime(2022, 5, 3, 16, 26, 13, 527638), 'یک هفته '), (datetime.datetime(2022, 4, 10, 16, 26, 13, 527638), 'یک ماه'), (datetime.datetime(2022, 2, 9, 16, 26, 13, 527638), ' سه ماه'), (datetime.datetime(2021, 11, 11, 16, 26, 13, 527638), 'شش ماه'), (datetime.datetime(2021, 5, 10, 16, 26, 13, 527638), 'یک سال')], default=django.utils.timezone.now, verbose_name='عضویت بی نهایت تا'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mybag',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
