# Generated by Django 4.0.3 on 2022-05-10 13:57

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0081_alter_user_special_user_alter_userprofile_mybag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(choices=[(datetime.datetime(2022, 5, 3, 18, 27, 14, 526268), 'یک هفته '), (datetime.datetime(2022, 4, 10, 18, 27, 14, 526268), 'یک ماه'), (datetime.datetime(2022, 2, 9, 18, 27, 14, 526268), ' سه ماه'), (datetime.datetime(2021, 11, 11, 18, 27, 14, 526268), 'شش ماه'), (datetime.datetime(2021, 5, 10, 18, 27, 14, 526268), 'یک سال')], default=django.utils.timezone.now, verbose_name='عضویت بی نهایت تا'),
        ),
    ]
