# Generated by Django 4.0.3 on 2022-05-10 17:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0083_alter_user_special_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(choices=[(datetime.datetime(2022, 5, 3, 21, 56, 39, 761402), 'یک هفته '), (datetime.datetime(2022, 4, 10, 21, 56, 39, 761402), 'یک ماه'), (datetime.datetime(2022, 2, 9, 21, 56, 39, 761402), ' سه ماه'), (datetime.datetime(2021, 11, 11, 21, 56, 39, 761402), 'شش ماه'), (datetime.datetime(2021, 5, 10, 21, 56, 39, 761402), 'یک سال')], default=django.utils.timezone.now, verbose_name='عضویت بی نهایت تا'),
        ),
    ]
