# Generated by Django 4.0.3 on 2022-05-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0084_alter_user_special_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='special_user',
        ),
    ]
