# Generated by Django 4.0.3 on 2022-05-11 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0087_alter_userprofile_puser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='puser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
