# Generated by Django 4.0.3 on 2022-05-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0091_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='puser',
        ),
    ]
