# Generated by Django 4.0.3 on 2022-05-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0093_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mybag',
            field=models.BigIntegerField(default=0, max_length=5),
        ),
    ]
