# Generated by Django 4.0.3 on 2022-05-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0095_alter_user_mybag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mybag',
            field=models.BigIntegerField(default=0, max_length=5),
        ),
    ]
