# Generated by Django 4.0.3 on 2022-05-13 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0097_alter_user_mybag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='عضویت بی نهایت تا'),
        ),
    ]
