# Generated by Django 4.0.3 on 2022-05-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0098_user_special_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentTime',
        ),
    ]
